/**
 * 内置默认审批规则表（纯数据，不依赖 node 模块）。
 *
 * 单独成文件是为了让浏览器也能 import 同一份表做命令高亮（issue #578）：
 * 前端不再维护内联黑名单，与服务端 evaluateApprovalRules 共用这一个事实源。
 */
import type { ApprovalRule } from "./approval-rules.js";

/**
 * 内置默认审批规则（与 server/tool-approval.ts 既有内置检测表保持 100% 同口径与同一 id）。
 */
export const DEFAULT_APPROVAL_RULES: ApprovalRule[] = [
	{
		id: "builtin.bash.rm-rf",
		enabled: true,
		tools: ["bash"],
		field: "command",
		match: "regex",
		value:
			"\\brm\\s+((-[a-zA-Z0-9]*[rf][a-zA-Z0-9]*|--recursive|--force)\\s+)+(((\\/)|(~)|(\\.\\.)|(\\*)|(\\.\\/))|[a-zA-Z]:[\\\\/])",
		action: "ask",
		label: "递归/强制删除 (rm -rf)",
		labelEn: "Recursive/force delete (rm -rf)",
		reason: "检测到高风险的递归/强制删除大范围路径命令 (rm -rf)",
		reasonEn: "Detected high-risk recursive/force deletion of wide paths (rm -rf)",
		categoryId: "bash.rm-rf",
		builtin: true,
	},
	{
		id: "builtin.bash.win-del",
		enabled: true,
		tools: ["bash"],
		field: "command",
		match: "regex",
		value: "\\b(del|rmdir|rd)\\s+[/\\-][fsq]",
		action: "ask",
		label: "Windows 强制删除 (del/rmdir/rd)",
		labelEn: "Windows force delete (del/rmdir/rd)",
		reason: "检测到高风险的 Windows 强制/递归删除目录命令 (del/rmdir/rd /s /q)",
		reasonEn: "Detected high-risk Windows force/recursive deletion command (del/rmdir/rd /s /q)",
		categoryId: "bash.win-del",
		builtin: true,
	},
	{
		id: "builtin.bash.disk",
		enabled: true,
		tools: ["bash"],
		field: "command",
		match: "regex",
		value: "\\b(mkfs|format\\s+[a-zA-Z]:|dd\\s+if=)",
		action: "ask",
		label: "磁盘格式化/底层写入",
		labelEn: "Disk format / raw block write",
		reason: "检测到磁盘格式化或底层块写入危险命令 (format/mkfs/dd)",
		reasonEn: "Detected dangerous disk formatting or raw block write command (format/mkfs/dd)",
		categoryId: "bash.disk",
		builtin: true,
	},
	{
		id: "builtin.bash.git-destructive",
		enabled: true,
		tools: ["bash"],
		field: "command",
		match: "regex",
		// git 全局选项前缀（-C <path> / -c k=v / --git-dir=…）、git.exe；push 强推 / +refspec / :branch 删远端；
		// checkout . / restore . / stash drop|clear 丢弃未提交修改（restore --staged 只取消暂存，排除）。
		// push 的参数区不跨 ; & | 换行，避免把后续命令里的 -f（如 `rm -f`）算进来（#578）。
		value:
			"\\bgit(?:\\.exe)?(?:\\s+(?:-[cC]\\s+\\S+|--[a-zA-Z-]+=\\S+))*\\s+(?:push\\s+(?:[^;&|\\n]*?\\s)?(?:--force|-[a-zA-Z0-9]*f)\\b|push\\s+(?:[^;&|\\n]*?\\s)?(?:\\+\\S+|:[^\\s/]\\S*)|reset\\s+--hard|clean\\s+(?:-[a-zA-Z]+\\s+)*-[a-zA-Z0-9]*f[a-zA-Z0-9]*|branch\\s+-[dD]\\b|checkout\\s+(?:--\\s+)?\\.(?=\\s|$|[;&|])|restore\\s+(?:--(?!staged\\b)\\S+\\s+)*\\.(?=\\s|$|[;&|])|stash\\s+(?:drop|clear)\\b)",
		action: "ask",
		label: "破坏性 Git 操作",
		labelEn: "Destructive git operation",
		reason:
			"检测到不可逆的破坏性 Git 操作 (force push / reset --hard / clean -f / checkout . / stash drop|clear / branch -D)",
		reasonEn:
			"Detected irreversible destructive Git operation (force push / reset --hard / clean -f / checkout . / stash drop|clear / branch -D)",
		categoryId: "bash.git-destructive",
		builtin: true,
	},
	{
		id: "builtin.bash.chmod",
		enabled: true,
		tools: ["bash"],
		field: "command",
		match: "regex",
		value: "\\bchmod\\s+(-R\\s+)?(777|000)\\b",
		action: "ask",
		label: "危险权限修改 (chmod)",
		labelEn: "Dangerous permission change (chmod)",
		reason: "检测到过度开放或全局破坏性的文件权限修改 (chmod 777/000)",
		reasonEn: "Detected overly permissive or globally destructive file permission change (chmod 777/000)",
		categoryId: "bash.chmod",
		builtin: true,
	},
	{
		id: "builtin.bash.system-redirect",
		enabled: true,
		tools: ["bash"],
		field: "command",
		match: "regex",
		value: ">\\s*(\\/etc\\/|\\/boot\\/|C:\\\\Windows)",
		action: "ask",
		label: "写入系统关键目录",
		labelEn: "Write into system directories",
		reason: "检测到重定向写入系统关键目录的危险操作",
		reasonEn: "Detected dangerous redirection writing into critical system directories",
		categoryId: "bash.system-redirect",
		builtin: true,
	},
	{
		id: "builtin.file.sensitive.env",
		enabled: true,
		tools: ["write", "edit", "edit_soft"],
		field: "path",
		match: "regex",
		value: "(^|[\\/\\\\])\\.env(\\.[a-zA-Z0-9_-]+)?$",
		action: "ask",
		label: "敏感配置 (.env)",
		labelEn: "Sensitive config (.env)",
		reason: "尝试修改敏感环境变量/密钥配置文件 (.env)",
		reasonEn: "Attempting to modify sensitive environment/secret configuration (.env)",
		categoryId: "file.sensitive.env",
		builtin: true,
	},
	{
		id: "builtin.file.sensitive.ssh",
		enabled: true,
		tools: ["write", "edit", "edit_soft"],
		field: "path",
		match: "regex",
		value: "(^|[\\/\\\\])(id_rsa|id_ed25519|authorized_keys|known_hosts)$",
		action: "ask",
		label: "SSH 密钥/凭据",
		labelEn: "SSH keys / credentials",
		reason: "尝试修改 SSH 密钥或认证凭据文件",
		reasonEn: "Attempting to modify SSH keys or authentication credentials",
		categoryId: "file.sensitive.ssh",
		builtin: true,
	},
	{
		id: "builtin.file.sensitive.shell",
		enabled: true,
		tools: ["write", "edit", "edit_soft"],
		field: "path",
		match: "regex",
		value: "(^|[\\/\\\\])(\\.bashrc|\\.zshrc|\\.profile|\\.bash_profile)$",
		action: "ask",
		label: "Shell 启动配置",
		labelEn: "Shell profile",
		reason: "尝试修改用户全局 Shell 启动配置文件",
		reasonEn: "Attempting to modify user global Shell profile configuration",
		categoryId: "file.sensitive.shell",
		builtin: true,
	},
	{
		id: "builtin.file.outside-workspace",
		enabled: true,
		tools: ["write", "edit", "edit_soft"],
		field: "path",
		match: "outside_workspace",
		value: "",
		action: "ask",
		label: "工作区外写入",
		labelEn: "Write outside workspace",
		reason: "尝试在工作区外部写入/修改文件",
		reasonEn: "Attempting to write/modify file outside the workspace",
		categoryId: "file.outside-workspace",
		builtin: true,
	},
];
