/**
 * 公开 MCP (Model Context Protocol) 服务器市场清单
 *
 * 精选官方与社区高质量、常用且稳定的 MCP 服务器，支持一键填入并配置到全局或项目。
 */

export interface PublicMcpServer {
	id: string;
	name: string;
	nameZh: string;
	description: string;
	descriptionZh: string;
	category: "core" | "dev" | "db" | "search" | "automation" | "tools";
	transport: "stdio" | "http";
	command?: string;
	args?: string[];
	env?: Array<{ key: string; value: string; placeholder?: string; required?: boolean }>;
	url?: string;
	package: string;
	official: boolean;
	requiresKey: boolean;
	homepage?: string;
}

export const PUBLIC_MCP_SERVERS: PublicMcpServer[] = [
	{
		id: "filesystem",
		name: "Filesystem",
		nameZh: "本地文件系统",
		description:
			"Secure file operations allowing reading, writing, and directory traversal with configurable allowed paths.",
		descriptionZh: "官方文件系统工具，支持安全的文件读写、内容检索与目录遍历。",
		category: "core",
		transport: "stdio",
		command: "npx",
		args: ["-y", "@modelcontextprotocol/server-filesystem", "."],
		package: "@modelcontextprotocol/server-filesystem",
		official: true,
		requiresKey: false,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
	},
	{
		id: "fetch",
		name: "Web Fetch",
		nameZh: "网页抓取与提取",
		description: "Fetches and converts web pages to clean Markdown for model consumption and research.",
		descriptionZh: "抓取指定 URL 网页正文并转换为结构化 Markdown 供智能体分析与阅读。",
		category: "search",
		transport: "stdio",
		command: "uvx",
		args: ["mcp-server-fetch"],
		package: "mcp-server-fetch",
		official: true,
		requiresKey: false,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
	},
	{
		id: "memory",
		name: "Knowledge Graph Memory",
		nameZh: "持久化知识记忆图谱",
		description: "Knowledge-graph based persistent memory system storing entities and relations locally.",
		descriptionZh: "基于实体与关联知识图谱的本地持久化记忆系统，赋予 AI 跨会话的长期记忆能力。",
		category: "core",
		transport: "stdio",
		command: "npx",
		args: ["-y", "@modelcontextprotocol/server-memory"],
		package: "@modelcontextprotocol/server-memory",
		official: true,
		requiresKey: false,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
	},
	{
		id: "github",
		name: "GitHub",
		nameZh: "GitHub 仓库与协作",
		description: "Interact with GitHub repositories, search code, manage issues, and review pull requests.",
		descriptionZh: "访问 GitHub 远程仓库、搜索代码、创建与检索 Issue、查看与操作 Pull Request。",
		category: "dev",
		transport: "stdio",
		command: "npx",
		args: ["-y", "@modelcontextprotocol/server-github"],
		package: "@modelcontextprotocol/server-github",
		env: [
			{
				key: "GITHUB_PERSONAL_ACCESS_TOKEN",
				value: "",
				placeholder: "ghp_xxxxxxxxxxxxxxxxxxxx",
				required: true,
			},
		],
		official: true,
		requiresKey: true,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
	},
	{
		id: "git",
		name: "Git Repository",
		nameZh: "本地 Git 版本控制",
		description: "Local Git repository operations including inspecting diffs, viewing history, and staging changes.",
		descriptionZh: "本地 Git 仓库操作，支持查看提交历史、变更 Diff、分支切换与暂存区管理。",
		category: "dev",
		transport: "stdio",
		command: "uvx",
		args: ["mcp-server-git", "--repository", "."],
		package: "mcp-server-git",
		official: false,
		requiresKey: false,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
	},
	{
		id: "sqlite",
		name: "SQLite Database",
		nameZh: "SQLite 数据库操作",
		description: "Query and inspect local SQLite databases with automatic schema discovery and safety checks.",
		descriptionZh: "连接并查询本地 SQLite 数据库文件，支持执行 SQL 语句、表结构探查与业务数据分析。",
		category: "db",
		transport: "stdio",
		command: "uvx",
		args: ["mcp-server-sqlite", "--db-path", "./app.db"],
		package: "mcp-server-sqlite",
		official: true,
		requiresKey: false,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite",
	},
	{
		id: "postgres",
		name: "PostgreSQL Database",
		nameZh: "PostgreSQL 数据库",
		description: "Read-only and read-write operations on PostgreSQL databases with schema inspection.",
		descriptionZh: "连接 PostgreSQL 数据库，支持执行参数化查询、表与索引分析及数据检索。",
		category: "db",
		transport: "stdio",
		command: "npx",
		args: ["-y", "@modelcontextprotocol/server-postgres", "postgresql://user:password@localhost:5432/dbname"],
		package: "@modelcontextprotocol/server-postgres",
		official: true,
		requiresKey: false,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
	},
	{
		id: "brave-search",
		name: "Brave Search",
		nameZh: "Brave 全球网页搜索",
		description: "Web search and local search capabilities powered by the privacy-preserving Brave Search API.",
		descriptionZh: "基于 Brave Search API 的全球互联网网页与资讯搜索工具，提供干净的搜索结果。",
		category: "search",
		transport: "stdio",
		command: "npx",
		args: ["-y", "@modelcontextprotocol/server-brave-search"],
		package: "@modelcontextprotocol/server-brave-search",
		env: [
			{
				key: "BRAVE_API_KEY",
				value: "",
				placeholder: "BSAxxxxxxxxxxxxxxxxxxxx",
				required: true,
			},
		],
		official: true,
		requiresKey: true,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
	},
	{
		id: "tavily",
		name: "Tavily AI Search",
		nameZh: "Tavily 智能搜索",
		description: "Search engine built specifically for AI agents, providing synthesized real-time web results.",
		descriptionZh: "专为 AI 智能体设计的搜索引擎，提供实时、高相关度、深度提炼的互联网内容检索结果。",
		category: "search",
		transport: "stdio",
		command: "uvx",
		args: ["mcp-server-tavily"],
		package: "mcp-server-tavily",
		env: [
			{
				key: "TAVILY_API_KEY",
				value: "",
				placeholder: "tvly-xxxxxxxxxxxxxxxxxxxx",
				required: true,
			},
		],
		official: false,
		requiresKey: true,
		homepage: "https://tavily.com",
	},
	{
		id: "puppeteer",
		name: "Puppeteer Web Browser",
		nameZh: "Puppeteer 浏览器自动化",
		description: "Automate browser interactions, take page screenshots, and interact with dynamic JavaScript apps.",
		descriptionZh: "无头浏览器自动化控制，支持截取网页长图、模拟点击、输入表单与渲染复杂动态页面。",
		category: "automation",
		transport: "stdio",
		command: "npx",
		args: ["-y", "@modelcontextprotocol/server-puppeteer"],
		package: "@modelcontextprotocol/server-puppeteer",
		official: true,
		requiresKey: false,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
	},
	{
		id: "docker",
		name: "Docker Manager",
		nameZh: "Docker 容器与镜像管理",
		description: "Inspect containers, check runtime logs, and manage local Docker images and volumes.",
		descriptionZh: "操作与监视本地 Docker 引擎，支持查询运行中容器、查看容器日志、启停与镜像管理。",
		category: "tools",
		transport: "stdio",
		command: "uvx",
		args: ["mcp-server-docker"],
		package: "mcp-server-docker",
		official: false,
		requiresKey: false,
		homepage: "https://github.com/modelcontextprotocol/servers",
	},
	{
		id: "slack",
		name: "Slack Integration",
		nameZh: "Slack 频道与消息互动",
		description: "Post messages, read channel transcripts, and manage conversations in Slack workspaces.",
		descriptionZh: "连接 Slack 工作区，支持读取频道历史消息、发送团队通知与讨论串交互。",
		category: "tools",
		transport: "stdio",
		command: "npx",
		args: ["-y", "@modelcontextprotocol/server-slack"],
		package: "@modelcontextprotocol/server-slack",
		env: [
			{
				key: "SLACK_BOT_TOKEN",
				value: "",
				placeholder: "xoxb-xxxxxxxxxxxxxxxxxxxx",
				required: true,
			},
		],
		official: true,
		requiresKey: true,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
	},
	{
		id: "time",
		name: "Time & Timezones",
		nameZh: "世界时间与时区计算",
		description: "Get current time in multiple formats, calculate offsets, and perform timezone conversions.",
		descriptionZh: "精准查询当前本地与 UTC 时间、全球时区转换及时间戳日期运算。",
		category: "tools",
		transport: "stdio",
		command: "uvx",
		args: ["mcp-server-time"],
		package: "mcp-server-time",
		official: false,
		requiresKey: false,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/time",
	},
	{
		id: "sentry",
		name: "Sentry Error Tracking",
		nameZh: "Sentry 异常与崩溃追踪",
		description: "Retrieve error traces, analyze crash dumps, and inspect recent issues from Sentry projects.",
		descriptionZh: "从 Sentry 平台检索应用报错堆栈、异常统计与崩溃事件，辅助快速定位生产故障。",
		category: "dev",
		transport: "stdio",
		command: "npx",
		args: ["-y", "@modelcontextprotocol/server-sentry"],
		package: "@modelcontextprotocol/server-sentry",
		env: [
			{
				key: "SENTRY_AUTH_TOKEN",
				value: "",
				placeholder: "sntrys_xxxxxxxxxxxxxxxxxxxx",
				required: true,
			},
		],
		official: true,
		requiresKey: true,
		homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/sentry",
	},
];
